# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FloraMessenger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FloraMessenger

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

end

target 'FloraMessenger-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FloraMessenger-tvOS

  target 'FloraMessenger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
